import sys
import os
import logging
from unittest.mock import patch

sys.path.append(os.getcwd())
logging.basicConfig(level=logging.DEBUG)

def verify_live_googl():
    print("--- LIVE VERIFICATION: GOOGL ---")
    from src.agents.analyst import AnalystAgent
    
    agent = AnalystAgent()
    
    # We want to see the LOGS generated by the agent.
    # We will override log_debug to print to stderr so we see it.
    def trace_log(msg):
        print(f"[TRACE] {msg}")
    agent.log_debug = trace_log
    
    # Run Agent
    print("Running Agent...")
    # Using a forceful prompt to simulate user action
    response = agent.run("Is GOOGL undervalued? Theme: undervalued tech")
    
    print("\n--- AGENT RESPONSE ---")
    print(response)

if __name__ == "__main__":
    verify_live_googl()
